[project]
name = "project1-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "krishazad07-commits", email = "krishazad07@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.17.0",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
]

[project.scripts]
project1-rag = "project1_rag:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
